[package]
name = "k1f-tg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.17.0", features = ["macros"] }
reqwest = { version = "0.13.4", features = ["json"] }
log = "0.4.33"
pinger = "2.1.4"
url = "2.5.8"
serde = "1.0.228"
lazy-regex = "3.6.0"
anyhow = "1.0.103"
thiserror = "2.0.18"
uuid = "1.23.4"
pretty_env_logger = "0.5.0"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros"] }
